# Generated by Django 2.2.5 on 2019-10-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmenu',
            name='mecatid',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
