# Generated by Django 2.2.5 on 2019-10-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_inmenu_mecatid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmenu',
            name='menuadd',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
