# Generated by Django 2.2.5 on 2019-10-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_inmenu_menuadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='inadmin',
            name='images',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='inposition_content',
            name='createttime',
            field=models.DateTimeField(null=True),
        ),
    ]
