# Generated by Django 2.2.5 on 2019-10-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20191005_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='inposition_content',
            name='content',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
