# Generated by Django 2.2.5 on 2019-10-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_inadmin_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='clicknum',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
